sudo: false
language: python

addons:
  postgresql: "9.3"

python:
  - "2.7"
  - "3.4"

env:
  - TRAVIS_DB=postgres
  - TRAVIS_DB=mysql

matrix:
  fast_finish: true

before_install:
  - pip install flake8 --use-mirrors
  - make flake

install:
  - if [[ $TRAVIS_DB == 'postgres' ]]; pip install psycopg2 ; fi
  - make install-test
  - pip install coveralls

before_script:
  - if [[ $TRAVIS_DB == 'postgres' ]]; then psql -c 'CREATE DATABASE travis_ci_test;' -U postgres ; fi
  - if [[ $TRAVIS_DB == 'mysql' ]]; then mysql -e 'CREATE DATABASE ralph CHARACTER SET utf8 COLLATE utf8_general_ci;' -uroot ; fi

script:
  - make coveralls

after_success:
  - coveralls

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/837fe61b536818b676ad
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
