language: python
env:
    - DJANGO_VERSION=1.4.16
    - DJANGO_VERSION=1.5.11
    - DJANGO_VERSION=1.6.8
matrix:
  allow_failures:
    - env: DJANGO_VERSION=1.4.16
    - env: DJANGO_VERSION=1.5.11
python:
  - "2.7"
# command to install dependencies, e.g. pip install -r requirements.txt --use-mirrors
install:
  - pip install git+https://github.com/allegro/django-bob@develop
  - pip install git+https://github.com/ar4s/bob-ajax-selects.git@new-form-of-url
  - make install
  - pip install git+https://github.com/allegro/ralph_assets.git@develop
  - pip install git+https://github.com/ar4s/InkPy.git@bumped-django-rq
  - pip install coveralls
  - pip install flake8


# command to run tests, e.g. python setup.py test
script: make test-with-coveralls
before_script:
  make flake

after_success:
  - coveralls

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/837fe61b536818b676ad
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
