sudo: false
language: python

addons:
  postgresql: "9.3"

python:
  - "2.7"
  - "3.4"
  - "pypy"

env:
  - TRAVIS_DB=postgres
  - TRAVIS_DB=mysql

matrix:
  fast_finish: true

before_install:
    - pip install flake8 --use-mirrors
    - make flake

install:
    - make install-test
    - pip install coveralls

script:
    - make coveralls

after_success:
  - coveralls

notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/837fe61b536818b676ad
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
